apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-app-cert
  namespace: sockshop
spec:
  secretName: xy-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: www.timileyindaso.com
  dnsNames:
  - www.timileyindaso.com
